### ISSUE TITLE
export2.php without valid parameter results full database dump

### ISSUE THREAD

**Issue by bekuno** [GeoKretyMap/Api#22]
When you call the export2.php skript without a valid parameter the you get a full database dump.
Is that really what you want?
I think it should better to result to a error message or empty data.

**Comment by kumy** [comment]
On GKM https://api.geokretymap.org/export2.php return a http 204 `No parameters.` However as you said, https://geokrety.org/export2.php return the whole database. This is probably a bug as it should restrict result to last `x` days and enforce some restriction.

**Comment by kumy** [comment]
Will migrate this issue to GK…

**Comment by kumy** [comment]
closing here
