### ISSUE TITLE
Extension of export2.php with parameter nr (tracking code)

### ISSUE THREAD

**Issue by bekuno** [GeoKretyMap/Api#23]
Please add the possibility to query the tracking code.
I would add this function in c:geo.

**Comment by kumy** [comment]
This is already implemented:

`https://api.geokretymap.org/nr/<tracking-code>`

https://github.com/GeoKretyMap/gkm-api-nginx/blob/898ba57e0695370f99e9ed73d85a1d8c4bf4e7e1/conf.d/api.geokretymap.org.conf#L134
